config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts

  root 'sessions#new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

    self.per_page = 5

    belongs_to :user

    validates :title,  presence: true
    validates :body,  presence: true
    validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token
  
  has_many :posts, dependent: :destroy

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, format: { with: EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :username, presence: true, uniqueness: {case_sensitive: false}

  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }

  def new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = self.new_token
    self.update(remember_digest: User.digest(self.remember_token))
  end

  def forget
    self.update(remember_digest: nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
    unless logged_in?
      redirect_to root_url
    end
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authorize

    def show
        @posts = Post.where('title like ?', "%#{params[:search]}%")
        render 'index'
    end

    def index
        # @posts = Post.all
        @posts = Post.paginate(page: params[:page])
    end
    def new
        @post = Post.new
    end

    def create
        @post = Post.new (post_params)
        @post.user = current_user
        if @post.save
            redirect_to posts_path
        else
            render 'new'
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
      
        redirect_to posts_path
    end

    private 
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :block_access, except: [:destroy]
    def create  
        @user = User.find_by(email: params[:session][:email].downcase)
        if @user && @user.authenticate(params[:session][:password])
            sign_in @user
        end
        redirect_to posts_path
    end

    def destroy
        sign_out
        redirect_to root_url
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]
  def new
    @user = User.new
  end

  def show
    @user = current_user
    render 'edit'
  end

  def create
    @user = User.new (user_params)
    if @user.save
      sign_in @user
      redirect_to posts_path
    else
      render 'new'
    end
  end


  def update
    @user = current_user

    if(params[:user][:current_password] == "")
      @user.errors.add(:current_password, "can't be blank")
      render 'edit'
      return
    end

    #Try to authenticate a user with the parameter "current_password"
    if @user && @user.authenticate(params[:user][:current_password])

      #Check if the user wants to change the password
      if(params[:user][:password] == "")
        params_without_password = user_params.except(:password, :password_confirmation)
        @user.update_attributes(params_without_password)
        redirect_to posts_path
        return
      
      #Check if password and password_confirmation match
      else
        if(params[:user][:password] == params[:user][:password_confirmation])
          @user.update_attributes(user_params)
        else 
          @user.errors.add(:password, "and Password confirmation don't match")
        end
      end
    else
      @user.errors.add(:current_password, "is invalid")
    end

    redirect_to posts_path
  end

  def edit
    @user = current_user
  end

  def destroy
    @user = current_user
    session[:user_id] = nil
    @user.destroy
    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def logged_in?
        !current_user.nil?
    end

    def sign_in(user)
        session[:user_id] = @user.id
    end

    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def block_access
        if current_user.present?
            redirect_to users_path
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-expand-md navbar-light bg-faded navbar-dark bg-dark">
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "Posts", posts_path,  class: "nav-link" %></li>
        <li><%= link_to current_user.username, edit_user_path(current_user), class: "nav-link" %></li>
        <li><%= link_to "Log out", sign_out_path, method: "delete", class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Posts", posts_path, class: "nav-link" %></li>
        <li><%= link_to "Log in", root_path, class: "nav-link" %></li>
      <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='container'>
  <h1> Posts </h1>


 <%= form_tag '/posts/search', method: :get do %>
  <div class='field'>
    <%= text_field_tag :search, nil %>
  </div>
<% end %>

<%= link_to 'Create post', new_post_path, class: "btn btn-primary"  %>

  <% if @posts.length > 0 %>
    <% @posts.each do |p| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= p.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= p.user.username %></h6>
          <p class="card-text"><%= p.body %></p>

          <% if p.user_id == current_user.id %>
            <a href="#" class="card-link">Edit</a>
            <%= link_to 'Destroy', p, :method => :delete, data: {:confirm => "Are you sure?" } %>

          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer  %>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>

    <% end %>
    
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div class="field">
        <%= f.label :body %>
        <%= f.text_field :body %>
    </div>

     <div class="field">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
    </div>


    <div class="actions">
        <%= f.submit "Create Post"%>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>

    <h1>Edit User</h1>

    <% if @user.errors.any? %>
        <h2><%= @user.errors.count %> error prohibited this user from being saved:</h2>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    <% end %>
    
    <%= form_for @user, url: user_path, method: :put do |f| %>
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>
        <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email %>
        </div>
        <div class="field">
            <%= f.label :password, "Password (leave blank if you don't want to change it)" %>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
        </div>

        <div class="field">
            <%= f.label :current_password, "Current password (we need your current password to confirm your changes)" %>
            <%= f.password_field :current_password %>
        </div>

        <div class="actions">
            <%= f.submit "Update"%>
        </div>

        <% end %>

        <h2>Cancel my account</h2>
        <h3>Unhappy?</h3>
        <%= link_to 'Cancel my account', '/users/destroy', method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/users/new.html.erb
<div class='container'>
    <%= form_for @user, :url => url_for(:controller => 'users', :action => 'create') do |f| %>
        <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>

        <% end %>
        
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>
        <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email %>
        </div>
        <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
        </div>
        
        <div class="actions">
            <%= f.submit "Signup"%>
        </div>
    <% end %>
</div>